version: '3'

services:
  spk-emb-dev:
    build: .
    container_name: spk-emb-dev
    image: spk-emb-dev-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 18081-18090:18081-18090
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]